Repository MOKLETHUB/HacktoberFest2021, pull requests merged in 2021-10, with the labels that each got.

#1 PlaylistLagu- by Wisnu
  Go/PlayListLagu.md
Labels: hacktoberfest

#2 Update Ebooks.md
  Go/Ebooks.md
Labels: Hacktoberfest, hacktoberest-accepted

#4 update film
  Go/StreamingFilm.md
Labels: hacktoberfest, hacktoberfest-accepted

#6 update anime
  Go/StreamingAnime.md
Labels: hacktoberfest, hacktoberfest-accepted
